config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :homes do 
    collection do
      get 'dashboard'
    end
  end
  devise_for :users, controllers: {
    sessions: 'user/sessions',
    registrations: 'user/registrations',
    :passwords => "user/passwords"
  }

  authenticated :user do
    devise_scope :user do
      
      root :to => 'homes#index'

    end

  end 
  unauthenticated :user do
    devise_scope :user do
      get "/" => "homes#index"
    end
  end
  
  get '/homes/about'
  post "subscriptions/webhook"
  get '/schools/subregion_options' => 'schools#subregion_options'
  get '/students/subregion_options' => 'students#subregion_options'
  devise_scope :user do
    get '/user/registrations/subregion_options' => 'user/registrations#subregion_options'
  end
  get '/students/:id/view_pdf', to: 'students#view_pdf', as: :view_pdf
  get '/students/checkemail', to: 'students#checkemail', as: :checkemail
  get '/schools/checkemail', to: 'students#checkemail', as: :checkemail_school
  get 'schools/user_detail_copy'
  get 'schools/school_detail_copy'
  
  resources :schools do
    resources :students    
  end

  controller :pages do
    get :about
    get :contact, to: 'pages#contact'
    post 'contact', to: 'pages#create'
  end

  
  resources :subscriptions
  resources :plans
  resources :transactions
  

end

app/models/student.rb
class Student < ActiveRecord::Base
require 'date'
#before_update :dob_cannot_be_current
	#validates :dob,:presence => true
	#validates_date :dob, presence: true, date: { after_or_equal_to: Proc.new { Date.today }, message: "must be at least #{(Date.today + 1).to_s}" }, on: :create, on: :update
	validates :first_name,:last_name,:presence => true
	# validates :zip,numericality: { only_integer: true ,message:"Zip code should be numeric"},length: { is: 5 ,message: "Zip code length should be 5"}
	validates :email, uniqueness: true
	# validates :phone,numericality:{ only_integer: true ,message:"Phone number should be numeric"},length: { is: 10 ,message: "Phone number length should be 10"}
	belongs_to :school
	validates :school_id,  :presence => {:message => "Please select a school" }
	#validates :dob, :presence => true, format: { with:  /(0[1-9]|[12][0-9]|3[01])[- /.](0[1-9]|1[012])[- /.](19|20)\d\d/}
	validates_presence_of :dob
	#validates_presence_of :dob, :with => /\A\d{2}(\.|-)\d{2}(\.|-)\d{4}\Z/i, :message => "Date incorrect"
	validates_presence_of :enroll_date
	validates_presence_of :graduation_date
	
	validate :today_is_after_dob

private

def today_is_after_dob
	
	return if dob.blank? 
	return if enroll_date.blank? 
	return if graduation_date.blank? 
	@dob = Date.strptime(dob, '%m/%d/%Y')
	if @dob>=Date.current 
		errors.add(:dob, "Date of Birth can't be Current Date and Future Date")
	end		

	@enroll_date=Date.strptime(enroll_date, '%m/%d/%Y')
	if @dob>=@enroll_date
		errors.add(:enroll_date, "Enrollment date must be greater than Date of Birth") 
	end

	@graduation_date=Date.strptime(graduation_date, '%m/%d/%Y')
	if @enroll_date>=@graduation_date
		errors.add(:graduation_date, "Graduation date can't be less than Enrollment date") 
	end 

end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	before_filter :authenticate_user!,except:[:subregion_options]
  load_and_authorize_resource except:[:subregion_options]
  def index
    @school = School.find(params[:school_id])
    @student = @school.students
  end
  def new 
    @school = School.find(params[:school_id])
    @student = @school.students.new
  end
  def checkemail
    if Student.where('email = ?', params[:email]).count == 0
     render json: {:email=>'not exist'}
   else
     render json: {:email=>'exist'}
   end
 end
 def show
  @school = School.find(params[:school_id])
  @student = @school.students.find(params[:id])
  respond_to do |format|
   format.html
   format.pdf do
    @pdf = render_to_string pdf: "student" ,:template => 'students/show.html.erb', 
    			# print_media_type: true ,
    			layout:''
    			send_data(@pdf, :filename => @student.first_name,  :type=>"application/pdf")
    		end
      end
    end

    def edit
      @school = School.find(params[:school_id])
      @student = @school.students.find(params[:id])
    end
    def update
      grade=[]
      credit=[]
      gpa_points=[]
      gpa_credit=[]
      total_credits=[]
      cumulative_gpa=[]
      a=0
      academic_params[:grade].each_index.map do |val|
        if academic_params[:honors][val]=='AP'
          ap=1 
        elsif academic_params[:honors][val]=='Honors'
          ap=0.5
        else
          ap=0
        end
        case academic_params[:grade][val]
        when 'A+'   
          grade[val] = 4.3+ap
          credit[val] = academic_params[:credits][val].to_f
        when 'A'  
          grade[val] = 4+ap
          credit[val] = academic_params[:credits][val].to_f
        when 'A-'   
          grade[val] = 3.7+ap
          credit[val] = academic_params[:credits][val].to_f
        when 'B+'  
          grade[val] = 3.3+ap
          credit[val] = academic_params[:credits][val].to_f
        when 'B'  
          grade[val] = 3+ap
          credit[val] = academic_params[:credits][val].to_f
        when 'B-'   
          grade[val] = 2.7+ap
          credit[val] = academic_params[:credits][val].to_f
        when 'C+'    
          grade[val] = 2.3+ap
          credit[val] = academic_params[:credits][val].to_f
        when 'C'    
          grade[val] = 2+ap
          credit[val] = academic_params[:credits][val].to_f
        when 'C-'    
          grade[val] = 1.7+ap
          credit[val] = academic_params[:credits][val].to_f
        when 'D+'   
          grade[val] = 1.3+ap
          credit[val] = academic_params[:credits][val].to_f
        when 'D'   
          grade[val] = 1+ap
          credit[val] = academic_params[:credits][val].to_f
        when 'D-'   
          grade[val] = 0.7+ap
          credit[val] = academic_params[:credits][val].to_f
        when 'F'   
          grade[val] = 0+ap
          credit[val] = academic_params[:credits][val].to_f
        when 'CR'   
          grade[val] = 0+ap
          credit[val] = academic_params[:credits][val].to_f
          a=academic_params[:credits][val].to_f+a
        when 'NC'    
          grade[val] = 0+ap
          credit[val] = academic_params[:credits][val].to_f
          a=academic_params[:credits][val].to_f+a
        when 'W'    
          grade[val] = 0+ap
          credit[val] = academic_params[:credits][val].to_f
          a=academic_params[:credits][val].to_f+a
        when 'I'   
          grade[val] = 0+ap
          credit[val] = academic_params[:credits][val].to_f
          a=academic_params[:credits][val].to_f+a
        end
      end
      gpa_points[0]=grade.inject{|sum,x| sum+x}
      total_credits[0]=credit.inject{|sum,x| sum+x}
      gpa_credit[0]=total_credits[0]-a
      cumulative_gpa[0]=gpa_points[0]/gpa_credit[0]
      cumulative_gpa[0]=cumulative_gpa[0].round(2)
      gpa_points[0]=gpa_points[0].round(2)
      
      @school = School.find(params[:school_id])
      @student = Student.find(params[:id])
      if @student.update student_params.merge(grad_name: academic_params["grad_name"],completion_year: academic_params["completion_year"],description: academic_params["description"],subject: academic_params["subject"],course_name: academic_params["course_name"],honors: academic_params["honors"],grade: academic_params["grade"],credits: academic_params["credits"],total_credit: total_credits,gpa_credit: gpa_credit,gpa_points: gpa_points,cumulative_gpa: cumulative_gpa)
       redirect_to  edit_school_student_path(@school,@student), :notice => "Student details updated successfully" 
     else
       render 'edit'
     end
   end
   def destroy
    @school = School.find(params[:school_id])
    @student = @school.students.find(params[:id])
    @student.destroy
    redirect_to school_students_path 
  end
  def view_pdf
    @student = Student.find(params[:id])
    @school = School.find(@student.school_id)

    respond_to do |format|
      format.html
      format.pdf do
       @pdf = render_to_string pdf: "student" ,:template => 'students/view_pdf.html.erb' ,disable_internal_links: true,disable_external_links: true,
       print_media_type: true 
       send_data(@pdf, :filename => @student.first_name+'.pdf',  :type=>"application/pdf")
     end
   end
 end
 def create
  grade=[]
  credit=[]
  gpa_points=[]
  gpa_credit=[]
  total_credits=[]
  cumulative_gpa=[]
  a=0
  academic_params[:grade].each_index.map do |val|
    if academic_params[:honors][val]=='AP'
          ap=1 
        elsif academic_params[:honors][val]=='Honors'
          ap=0.5
        else
          ap=0
        end
    case academic_params[:grade][val]
    when 'A+'   
      grade[val] = 4.3+ap
      credit[val] = academic_params[:credits][val].to_f
    when 'A'  
      grade[val] = 4+ap
      credit[val] = academic_params[:credits][val].to_f
    when 'A-'   
      grade[val] = 3.7+ap
      credit[val] = academic_params[:credits][val].to_f
    when 'B+'  
      grade[val] = 3.3+ap
      credit[val] = academic_params[:credits][val].to_f
    when 'B'  
      grade[val] = 3+ap
      credit[val] = academic_params[:credits][val].to_f
    when 'B-'   
      grade[val] = 2.7+ap
      credit[val] = academic_params[:credits][val].to_f
    when 'C+'    
      grade[val] = 2.3+ap
      credit[val] = academic_params[:credits][val].to_f
    when 'C'    
      grade[val] = 2+ap
      credit[val] = academic_params[:credits][val].to_f
    when 'C-'    
      grade[val] = 1.7+ap
      credit[val] = academic_params[:credits][val].to_f
    when 'D+'   
      grade[val] = 1.3+ap
      credit[val] = academic_params[:credits][val].to_f
    when 'D'   
      grade[val] = 1+ap
      credit[val] = academic_params[:credits][val].to_f
    when 'D-'   
      grade[val] = 0.7+ap
      credit[val] = academic_params[:credits][val].to_f
    when 'F'   
      grade[val] = 0+ap
      credit[val] = academic_params[:credits][val].to_f
    when 'CR'   
      grade[val] = 0+ap
      credit[val] = academic_params[:credits][val].to_f
      a=academic_params[:credits][val].to_f+a
    when 'NC'    
      grade[val] = 0+ap
      credit[val] = academic_params[:credits][val].to_f
      a=academic_params[:credits][val].to_f+a
    when 'W'    
      grade[val] = 0+ap
      credit[val] = academic_params[:credits][val].to_f
      a=academic_params[:credits][val].to_f+a
    when 'I'   
      grade[val] = 0+ap
      credit[val] = academic_params[:credits][val].to_f
      a=academic_params[:credits][val].to_f+a
    end
  end
  gpa_points[0]=grade.inject{|sum,x| sum+x}
  total_credits[0]=credit.inject{|sum,x| sum+x}
  gpa_credit[0]=total_credits[0]-a
  cumulative_gpa[0]=gpa_points[0]/gpa_credit[0]
  cumulative_gpa[0]=cumulative_gpa[0].round(2)

  @school = School.find(params[:school_id])
  @student = @school.students.new student_params.merge(grad_name: academic_params["grad_name"],completion_year: academic_params["completion_year"],description: academic_params["description"],subject: academic_params["subject"],course_name: academic_params["course_name"],honors: academic_params["honors"],grade: academic_params["grade"],credits: academic_params["credits"],total_credit: total_credits ,gpa_points: gpa_points, gpa_credit:gpa_credit,cumulative_gpa:cumulative_gpa)
  if @student.save
    redirect_to  school_students_path 
  else
    render 'new'
  end 
end 

def subregion_options
  render partial: 'subregion_select'
end
private
def student_params
  params.require(:student).permit(:first_name , :middle_name , :last_name, :dob, :address1 , :address2 ,:address3 , :country, :state , :city , :zip, :phone ,:email, :enroll_date ,:graduation_date)
end
def academic_params
  params.permit(:grad_name => [] ,:completion_year => [], :description =>[] , :subject => [] , :course_name => [] , :honors => [] , :grade => [] , :credits => [] , :total_credit => [] , :gpa_credit => [] , :gpa_points => [] , :cumulative_gpa => [])
end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_subregion_select.html.erb
<div id="order_state_code_wrapper">
  <% parent_region ||= params[:parent_region] %>
  <% country = Carmen::Country.coded(parent_region) %>

  <% if country.nil? %>
    <em class="form-control">Please select a country above</em>
  <% elsif country.subregions? %>
    <%= subregion_select(:student , :state, parent_region,{},{:class=>"form-control"}) %>
  <% else %>
    <%= text_field(:student , :state) %>
  <% end %>
</div>

app/views/students/edit.html.erb
<%= render 'studentedit_form'%>

app/views/students/index.html.erb

<div class="mini-title-head-bar logiq1">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<ol class="greybeadcrub">
					<ul class="greybeadcrub"><li><%= link_to 'Home',root_path %></li>
						<li class="active">Students</li>
					</ul>                    
				</ol>
			</div>
		</div>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-lg-10 col-md-10 col-sm-10 col-xs-12 col-md-offset-1">
		<% if alert %>
	    	<center><p class="alert alert-danger"><%= alert %></p></center>
	    <% end %>
	    <% if flash[:notice] %>
	    	<center><p class="alert alert-success"><%= flash[:notice] %></p></center>
	    <% end %>
			<div class="panel panel-default">
				<div class="panel-heading"> <strong class="">Students</strong>
				</div>
					<div class="studentscroll">
					<table class="table table-striped table-responsive table-bordered">
						<tbody>
							<tr>
								<td><strong>Name</strong></td>
								<td align="center" valign="middle"><strong>Date of Birth</strong></td>
								<td colspan="4" align="left" valign="middle"></td>
							</tr>
							<% @student.each do |student|%>
							<tr>
								<td>
									<%= student.first_name %> <%= student.middle_name %> <%= student.last_name %>
								</td>
								<td align="center" valign="middle">
									<%= student.dob%>
								</td>
								<td align="center" valign="middle">			
									<%= link_to school_student_path(student.school,student.id),:class=>"btn btn-info btn-xs" do %>
										<i><span class="glyphicon glyphicon-eye-open"></span></i> View
                  					<%end%>
								</td>
								<td align="center" valign="middle">
									<%= link_to edit_school_student_path(student.school,student.id),:class=>"btn btn-info btn-xs" do %>
										<i><span class="glyphicon glyphicon-edit"></span></i> Edit
                  					<%end%>
								</td>
								<td align="center" valign="middle">
									<%= link_to school_student_path(student.school,student.id),method: :delete , data: {confirm: ' Are you sure you want to delete student record?'} , :class=>"btn btn-danger btn-xs" do %>
										<i><span class="glyphicon glyphicon-trash"></span></i> Delete
                  					<%end%>
								</td>
								<td align="center" valign="middle">
									<%= link_to view_pdf_path(student),:class=>"btn btn-success btn-xs" do %>
										<i><span class="glyphicon glyphicon-print"></span></i> View Pdf
                  					<%end%> 
								</td>
							</tr>
							
							<%end%>
						</tbody></table>
						</div>
						<div class="panel-footer txtalyn3">
							<%= link_to 'Add New Student',new_school_student_path(@school.id), class: 'btn btn-primary btn-xs'%>
						</div>
					</div>
				</div>

			</div>
		</div>



app/views/students/new.html.erb
<%= render 'student_form'%>

app/views/students/show.html.erb

<div class="mini-title-head-bar logiq1">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<ol class="greybeadcrub">
					<ul class="greybeadcrub"><li><%= link_to 'Home',root_path %></li>
						<li class="active">Student Details</li>
					</ul>                   
				</ol>
			</div>
		</div>
	</div>
</div>



<div class="container">
	<div class="row">
		<div class="col-md-6 col-sm-6">
			<% if alert %>
		    	<center><p class="alert alert-danger"><%= alert %></p></center>
		    <% end %>
		    <% if flash[:notice] %>
		    	<center><p class="alert alert-success"><%= flash[:notice] %></p></center>
		    <% end %>
			<div class="panel panel-default">
				<div class="panel-heading"> <strong class=""> Student Details</strong>
				</div>
					<table class="table table-striped table-responsive table-bordered">
						<tbody><tr>
							<th class="showdt1">Name</th><td><%=@student.first_name%> <%=@student.middle_name%> <%=@student.last_name%></td>
						</tr>
						<tr>
							<th class="showdt1">Date of Birth</th><td><%=@student.dob%> </td>
						</tr>
						<tr>
								<th class="showdt1">Address</th><td><%=@student.address1%> &nbsp; <%=@student.address2%>  &nbsp; <%=@student.address3%></td>
							</tr>
						<tr>
							<th class="showdt1">Country</th><td><%=@country = Carmen::Country.coded(@student.country)%></td>
						</tr>
						<tr>
							<th class="showdt1">State</th>
							<td>
								<% @subregions = @country.subregions %>
                    			<% @state = @subregions.coded(@student.state) %>
								<%if @state.blank?%>
									<%= @student.state%>				
								<%else%>
									<%=@state.name%>
								<%end%>				
							</td>
						</tr>
						<tr>
							<th class="showdt1">City</th><td><%=@student.city%></td>
						</tr>
						<tr>
							<th class="showdt1">Zip</th><td><%=@student.zip%></td>
						</tr>
						<tr>
							<th class="showdt1">Phone</th><td><%=@student.phone%></td>
						</tr>
						<tr>
							<th class="showdt1">Email id</th><td><%=@student.email%></td>
						</tr>
						<tr>
							<th class="showdt1">Enrollment Date</th><td><%=@student.enroll_date%></td>
						</tr>
						<tr>
							<th class="showdt1">Graduation Date</th><td><%=@student.graduation_date%></td>
						</tr>
					</tbody></table>

				</div>
			</div>
			<div class="col-md-6 col-sm-6">
				<div class="panel panel-default">
					<div class="panel-heading"> <strong class=""> Academic Details</strong>

					</div>
					<%x=1%>
					<%@student.subject.length.times do|academic|%>
					<table class="table table-striped table-responsive table-bordered"><tbody>
						<tr>
              <th colspan="2" class="clasq1">Class : <%= x %></th>
            </tr>
					
					<tr>
						<th class="showdt1">Year</th><td><%=@student.completion_year[academic]%> </td>
					</tr>

					<tr>
						<th class="showdt1">Subject</th><td><%=@student.subject[academic]%></td>
					</tr>
					<tr>
						<th class="showdt1">Course Name</th><td><%=@student.course_name[academic]%></td>
					</tr>
					<tr>
						<th class="showdt1">Honors</th><td><%=@student.honors[academic]%></td>
					</tr>
					<tr>
						<th class="showdt1">Grade</th><td><%=@student.grade[academic]%></td>
					</tr>
					<tr>
						<th class="showdt1">Credits</th><td><%=@student.credits[academic]%></td>
					</tr>

				</tbody></table>
				<% x = x+1%>
			<%end%>
				<div class="panel-footer txtalyn3">
					<%= link_to "Back", :back, :class=>"btn btn-info" %>
				</div>
			</div>
		</div>

	</div>
</div>