config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :homes do 
    collection do
      get 'dashboard'
    end
  end
  devise_for :users, controllers: {
    sessions: 'user/sessions',
    registrations: 'user/registrations',
    :passwords => "user/passwords"
  }

  authenticated :user do
    devise_scope :user do
      
      root :to => 'homes#index'

    end

  end 
  unauthenticated :user do
    devise_scope :user do
      get "/" => "homes#index"
    end
  end
  
  get '/homes/about'
  post "subscriptions/webhook"
  get '/schools/subregion_options' => 'schools#subregion_options'
  get '/students/subregion_options' => 'students#subregion_options'
  devise_scope :user do
    get '/user/registrations/subregion_options' => 'user/registrations#subregion_options'
  end
  get '/students/:id/view_pdf', to: 'students#view_pdf', as: :view_pdf
  get '/students/checkemail', to: 'students#checkemail', as: :checkemail
  get '/schools/checkemail', to: 'students#checkemail', as: :checkemail_school
  get 'schools/user_detail_copy'
  get 'schools/school_detail_copy'
  
  resources :schools do
    resources :students    
  end

  controller :pages do
    get :about
    get :contact, to: 'pages#contact'
    post 'contact', to: 'pages#create'
  end

  
  resources :subscriptions
  resources :plans
  resources :transactions
  

end

app/models/student.rb
class Student < ActiveRecord::Base
require 'date'
#before_update :dob_cannot_be_current
	#validates :dob,:presence => true
	#validates_date :dob, presence: true, date: { after_or_equal_to: Proc.new { Date.today }, message: "must be at least #{(Date.today + 1).to_s}" }, on: :create, on: :update
	validates :first_name,:last_name,:presence => true
	# validates :zip,numericality: { only_integer: true ,message:"Zip code should be numeric"},length: { is: 5 ,message: "Zip code length should be 5"}
	validates :email, uniqueness: true
	# validates :phone,numericality:{ only_integer: true ,message:"Phone number should be numeric"},length: { is: 10 ,message: "Phone number length should be 10"}
	belongs_to :school
	validates :school_id,  :presence => {:message => "Please select a school" }
	#validates :dob, :presence => true, format: { with:  /(0[1-9]|[12][0-9]|3[01])[- /.](0[1-9]|1[012])[- /.](19|20)\d\d/}
	validates_presence_of :dob
	#validates_presence_of :dob, :with => /\A\d{2}(\.|-)\d{2}(\.|-)\d{4}\Z/i, :message => "Date incorrect"
	validates_presence_of :enroll_date
	validates_presence_of :graduation_date
	
	validate :today_is_after_dob

private

def today_is_after_dob
	
	return if dob.blank? 
	return if enroll_date.blank? 
	return if graduation_date.blank? 
	@dob = Date.strptime(dob, '%m/%d/%Y')
	if @dob>=Date.current 
		errors.add(:dob, "Date of Birth can't be Current Date and Future Date")
	end		

	@enroll_date=Date.strptime(enroll_date, '%m/%d/%Y')
	if @dob>=@enroll_date
		errors.add(:enroll_date, "Enrollment date must be greater than Date of Birth") 
	end

	@graduation_date=Date.strptime(graduation_date, '%m/%d/%Y')
	if @enroll_date>=@graduation_date
		errors.add(:graduation_date, "Graduation date can't be less than Enrollment date") 
	end 

end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	before_filter :authenticate_user!,except:[:subregion_options]
  load_and_authorize_resource except:[:subregion_options]
  def index
    @school = School.find(params[:school_id])
    @student = @school.students
  end
  def new 
    @school = School.find(params[:school_id])
    @student = @school.students.new
  end
  def checkemail
    if Student.where('email = ?', params[:email]).count == 0
     render json: {:email=>'not exist'}
   else
     render json: {:email=>'exist'}
   end
 end
 def show
  @school = School.find(params[:school_id])
  @student = @school.students.find(params[:id])
  respond_to do |format|
   format.html
   format.pdf do
    @pdf = render_to_string pdf: "student" ,:template => 'students/show.html.erb', 
    			# print_media_type: true ,
    			layout:''
    			send_data(@pdf, :filename => @student.first_name,  :type=>"application/pdf")
    		end
      end
    end

    def edit
      @school = School.find(params[:school_id])
      @student = @school.students.find(params[:id])
    end
    def update
      grade=[]
      credit=[]
      gpa_points=[]
      gpa_credit=[]
      total_credits=[]
      cumulative_gpa=[]
      a=0
      academic_params[:grade].each_index.map do |val|
        if academic_params[:honors][val]=='AP'
          ap=1 
        elsif academic_params[:honors][val]=='Honors'
          ap=0.5
        else
          ap=0
        end
        case academic_params[:grade][val]
        when 'A+'   
          grade[val] = 4.3+ap
          credit[val] = academic_params[:credits][val].to_f
        when 'A'  
          grade[val] = 4+ap
          credit[val] = academic_params[:credits][val].to_f
        when 'A-'   
          grade[val] = 3.7+ap
          credit[val] = academic_params[:credits][val].to_f
        when 'B+'  
          grade[val] = 3.3+ap
          credit[val] = academic_params[:credits][val].to_f
        when 'B'  
          grade[val] = 3+ap
          credit[val] = academic_params[:credits][val].to_f
        when 'B-'   
          grade[val] = 2.7+ap
          credit[val] = academic_params[:credits][val].to_f
        when 'C+'    
          grade[val] = 2.3+ap
          credit[val] = academic_params[:credits][val].to_f
        when 'C'    
          grade[val] = 2+ap
          credit[val] = academic_params[:credits][val].to_f
        when 'C-'    
          grade[val] = 1.7+ap
          credit[val] = academic_params[:credits][val].to_f
        when 'D+'   
          grade[val] = 1.3+ap
          credit[val] = academic_params[:credits][val].to_f
        when 'D'   
          grade[val] = 1+ap
          credit[val] = academic_params[:credits][val].to_f
        when 'D-'   
          grade[val] = 0.7+ap
          credit[val] = academic_params[:credits][val].to_f
        when 'F'   
          grade[val] = 0+ap
          credit[val] = academic_params[:credits][val].to_f
        when 'CR'   
          grade[val] = 0+ap
          credit[val] = academic_params[:credits][val].to_f
          a=academic_params[:credits][val].to_f+a
        when 'NC'    
          grade[val] = 0+ap
          credit[val] = academic_params[:credits][val].to_f
          a=academic_params[:credits][val].to_f+a
        when 'W'    
          grade[val] = 0+ap
          credit[val] = academic_params[:credits][val].to_f
          a=academic_params[:credits][val].to_f+a
        when 'I'   
          grade[val] = 0+ap
          credit[val] = academic_params[:credits][val].to_f
          a=academic_params[:credits][val].to_f+a
        end
      end
      gpa_points[0]=grade.inject{|sum,x| sum+x}
      total_credits[0]=credit.inject{|sum,x| sum+x}
      gpa_credit[0]=total_credits[0]-a
      cumulative_gpa[0]=gpa_points[0]/gpa_credit[0]
      cumulative_gpa[0]=cumulative_gpa[0].round(2)
      gpa_points[0]=gpa_points[0].round(2)
      
      @school = School.find(params[:school_id])
      @student = Student.find(params[:id])
      if @student.update student_params.merge(grad_name: academic_params["grad_name"],completion_year: academic_params["completion_year"],description: academic_params["description"],subject: academic_params["subject"],course_name: academic_params["course_name"],honors: academic_params["honors"],grade: academic_params["grade"],credits: academic_params["credits"],total_credit: total_credits,gpa_credit: gpa_credit,gpa_points: gpa_points,cumulative_gpa: cumulative_gpa)
       redirect_to  edit_school_student_path(@school,@student), :notice => "Student details updated successfully" 
     else
       render 'edit'
     end
   end
   def destroy
    @school = School.find(params[:school_id])
    @student = @school.students.find(params[:id])
    @student.destroy
    redirect_to school_students_path 
  end
  def view_pdf
    @student = Student.find(params[:id])
    @school = School.find(@student.school_id)

    respond_to do |format|
      format.html
      format.pdf do
       @pdf = render_to_string pdf: "student" ,:template => 'students/view_pdf.html.erb' ,disable_internal_links: true,disable_external_links: true,
       print_media_type: true 
       send_data(@pdf, :filename => @student.first_name+'.pdf',  :type=>"application/pdf")
     end
   end
 end
 def create
  grade=[]
  credit=[]
  gpa_points=[]
  gpa_credit=[]
  total_credits=[]
  cumulative_gpa=[]
  a=0
  academic_params[:grade].each_index.map do |val|
    if academic_params[:honors][val]=='AP'
          ap=1 
        elsif academic_params[:honors][val]=='Honors'
          ap=0.5
        else
          ap=0
        end
    case academic_params[:grade][val]
    when 'A+'   
      grade[val] = 4.3+ap
      credit[val] = academic_params[:credits][val].to_f
    when 'A'  
      grade[val] = 4+ap
      credit[val] = academic_params[:credits][val].to_f
    when 'A-'   
      grade[val] = 3.7+ap
      credit[val] = academic_params[:credits][val].to_f
    when 'B+'  
      grade[val] = 3.3+ap
      credit[val] = academic_params[:credits][val].to_f
    when 'B'  
      grade[val] = 3+ap
      credit[val] = academic_params[:credits][val].to_f
    when 'B-'   
      grade[val] = 2.7+ap
      credit[val] = academic_params[:credits][val].to_f
    when 'C+'    
      grade[val] = 2.3+ap
      credit[val] = academic_params[:credits][val].to_f
    when 'C'    
      grade[val] = 2+ap
      credit[val] = academic_params[:credits][val].to_f
    when 'C-'    
      grade[val] = 1.7+ap
      credit[val] = academic_params[:credits][val].to_f
    when 'D+'   
      grade[val] = 1.3+ap
      credit[val] = academic_params[:credits][val].to_f
    when 'D'   
      grade[val] = 1+ap
      credit[val] = academic_params[:credits][val].to_f
    when 'D-'   
      grade[val] = 0.7+ap
      credit[val] = academic_params[:credits][val].to_f
    when 'F'   
      grade[val] = 0+ap
      credit[val] = academic_params[:credits][val].to_f
    when 'CR'   
      grade[val] = 0+ap
      credit[val] = academic_params[:credits][val].to_f
      a=academic_params[:credits][val].to_f+a
    when 'NC'    
      grade[val] = 0+ap
      credit[val] = academic_params[:credits][val].to_f
      a=academic_params[:credits][val].to_f+a
    when 'W'    
      grade[val] = 0+ap
      credit[val] = academic_params[:credits][val].to_f
      a=academic_params[:credits][val].to_f+a
    when 'I'   
      grade[val] = 0+ap
      credit[val] = academic_params[:credits][val].to_f
      a=academic_params[:credits][val].to_f+a
    end
  end
  gpa_points[0]=grade.inject{|sum,x| sum+x}
  total_credits[0]=credit.inject{|sum,x| sum+x}
  gpa_credit[0]=total_credits[0]-a
  cumulative_gpa[0]=gpa_points[0]/gpa_credit[0]
  cumulative_gpa[0]=cumulative_gpa[0].round(2)

  @school = School.find(params[:school_id])
  @student = @school.students.new student_params.merge(grad_name: academic_params["grad_name"],completion_year: academic_params["completion_year"],description: academic_params["description"],subject: academic_params["subject"],course_name: academic_params["course_name"],honors: academic_params["honors"],grade: academic_params["grade"],credits: academic_params["credits"],total_credit: total_credits ,gpa_points: gpa_points, gpa_credit:gpa_credit,cumulative_gpa:cumulative_gpa)
  if @student.save
    redirect_to  school_students_path 
  else
    render 'new'
  end 
end 

def subregion_options
  render partial: 'subregion_select'
end
private
def student_params
  params.require(:student).permit(:first_name , :middle_name , :last_name, :dob, :address1 , :address2 ,:address3 , :country, :state , :city , :zip, :phone ,:email, :enroll_date ,:graduation_date)
end
def academic_params
  params.permit(:grad_name => [] ,:completion_year => [], :description =>[] , :subject => [] , :course_name => [] , :honors => [] , :grade => [] , :credits => [] , :total_credit => [] , :gpa_credit => [] , :gpa_points => [] , :cumulative_gpa => [])
end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/admin/students/edit.html.erb
    <div id="main_content">

      <%= form_for :student, url: admin_student_path ,method: :patch do|f|%>

      <fieldset class="inputs">
        <legend>
          <span>Edit Student Details</span>
        </legend>

        <ol>
         <li class="select input optional">
          <%= f.label :school_name %>
          <%= f.select :school_id, options_for_select(School.all.map{ |school| ["#{school.school_name}", school.id] }), :prompt=>'Please Select School'  %>
          <p class="inline-errors">
            <%=@student.errors[:school_id].join(",") %> 
          </p>
        </li>
        <li class="string input optional stringish">
          <%= f.label :first_name %>
          <%= f.text_field :first_name, autofocus: true %>
           <p id="first_name_error" class="inline-errors">
              <%=@student.errors[:first_name].join(",") %> 
            </p>
        </li>

        <li class="string input optional stringish">
          <%= f.label :middle_name %>
          <%= f.text_field :middle_name, autofocus: true %>
        </li>

        <li class="string input optional stringish">
          <%= f.label :last_name %>
          <%= f.text_field :last_name, autofocus: true %>
           <p id="last_name_error" class="inline-errors">
              <%=@student.errors[:last_name].join(",") %> 
            </p>
        </li>

        <li class="string input optional stringish">
          <%= f.label :dob %>
          <%= f.text_field :dob, autofocus: true,readonly: true %>
          <p id= "student_dob_error" class="inline-errors">
              <%=@student.errors[:dob].join(",") %> 
            </p>
        </li>

        <li class="string input optional stringish">
          <%= f.label :address_line_1 %> 
          <%= f.text_field :address1, autocomplete: "off" %>
        </li>

        <li class="string input optional stringish">
          <%= f.label :address_line_2 %> 
          <%= f.text_field :address2, autocomplete: "off" %>
        </li>

        <li class="string input optional stringish">
          <%= f.label :address_line_3 %> 
          <%= f.text_field :address3, autocomplete: "off" %>
        </li>

        <li class="string input optional stringish">
          <%= f.label :country %> 
          <%= f.select :country, region_options_for_select(only_us_and_canada,@student.country),{},:class=>"form-control" %>
        </li>


        <li class="string input optional stringish">
          <%= f.label :state %> 
          <%= f.text_field :state, autocomplete: "off" %>
        </li>

        <li class="string input optional stringish">
          <%= f.label :city %> 
          <%= f.text_field :city, autocomplete: "off" %>
        </li>


        <li class="string input optional stringish">
          <%= f.label :zip %> 
          <%= f.text_field :zip, autocomplete: "off" %>
          <p id="zip_error" class="inline-errors">
              <%=@student.errors[:zip].join(" and ") %> 
            </p>
        </li>

        <li class="string input optional stringish">
          <%= f.label :primary_phone %> 
          <%= f.text_field :phone, autocomplete: "off" %>
           <p id="phone_error" class="inline-errors">
              <%=@student.errors[:phone].join(" and ") %> 
            </p>
        </li>

        <li class="string input optional stringish">
          <%= f.label :email %>
          <%= f.email_field :email, autofocus: true %>
          <p id= "student_email_error" class="inline-errors">
            <%=@student.errors[:email].join(",") %> 
          </p>
        </li>

        <li class="string input optional stringish">
          <%= f.label :enroll_date %>
          <%= f.text_field :enroll_date,readonly: true%>
          <p id="student_enroll_date_error" class="inline-errors">
            <%=@student.errors[:enroll_date].join(",") %> 
          </p>
        </li>

        <li class="string input optional stringish">
          <%= f.label :graduation_date %>
          <%= f.text_field :graduation_date,readonly: true %>
           <p id ="student_graduation_date_error" class="inline-errors">
            <%=@student.errors[:graduation_date].join(",") %> 
          </p>
        </li>
      </ol>
      

      <h2>Classes </h2>

      <div class="input_fields_wrap">
        <% x=0%>
        <input type="button" class="add_field_button" value="Add Another Class">

        <% @student.subject.each do |stu|%>
        <% 
        if x==0
          cl="education"
        else
          cl = "education secondEdu"
        end
        %>
        <div class="<%= cl %>">
          <h3>Class <%= x+1%></h3>
          <% if x==0 %>
          <div style="clear:both;"></div>
          <%else%>
          <a href="javascript:void(0)" class="remove_field">Remove</a>
          <%end%>
          
          <div style="clear:both;"></div>
          <ol>
            



            <li class="string input optional stringish">
               <label for="completion_year">Year</label>

                <%= select_tag "completion_year[]", options_for_select([['Freshman ', 'Freshman'], ['Sophomore', 'Sophomore'],['Junior', 'Junior'],['Senior', 'Senior']],:selected => @student.completion_year[x]),:prompt=>'Please Select'%>
           </li>




           <li class="string input optional stringish">
              <label for="subject">Subject</label>
              <input type="text" name="subject[]" value= "<%= @student.subject[x] %>">
            </li>

            <li class="string input optional stringish">
              <label for="course_name">Course Name</label>
              <input type="text" name="course_name[]" value= "<%= @student.course_name[x] %>">
            </li>

            <li class="string input optional stringish">
            <label for="honors">Honors</label>
             <%= select_tag "honors[]", options_for_select([['No ', 'No'], ['Yes', 'Yes']],:selected =>  @student.honors[x])%>
           </li>
            <li class="string input optional stringish">
              <label for="grade">Grade</label>
                 <%= select_tag "grade[]", options_for_select([['A+ ', 'A+'], ['A', 'A'],['A-', 'A-'],['B+', 'B+'],['B', 'B'],['B-', 'B-'],['C+', 'C+'],['C', 'C'],['C-', 'C-'],['D+', 'D+'],['D', 'D'],['D-', 'D-'],['F', 'F'],['CR', 'CR'],['NC', 'NC'],['W', 'W'],['I', 'I']],:selected => @student.grade[x])%>
           </li>
           <li class="string input optional stringish">
             <label for="credit">Credit</label>
             <%= select_tag "credits[]", options_for_select([['0.5 ', '0.5'], ['1.0', '1.0'],['2.0 ', '2.0']],:selected => @student.credits[x])%>
             </li>
             <input type="hidden" name="total_credit[]" value= "<%= @student.total_credit[x] %>">
             <input type="hidden" name="gpa_credit[]" value= "<%= @student.gpa_credit[x] %>">
             <input type="hidden" name="gpa_points[]" value= "<%= @student.gpa_points[x] %>">
             <input type="hidden" name="cumulative_gpa[]" value= "<%= @student.cumulative_gpa[x] %>">
             
           </ol>
         </div>
         <% x=x+1%>
         <%end%>
       </div>
       
       <input type= "hidden" value= "<%=x%>" id="xval">
       <fieldset class="actions">
        <ol>
          <li id="student_edit_submit_action" class="action input_action ">
           <%= f.submit "Update" %>
         </li>
         <li class="cancel">
          <a href="/admin/students">Cancel</a>
        </li>
      </ol>
    </fieldset>
    <%end%>

  </div>

app/views/admin/students/new.html.erb
    <div id="main_content">

      <%= form_for :student,  url: admin_students_path   do|f|%>
      <fieldset class="inputs">
        <legend>
          <span>Student Details</span>
        </legend>
        
        <ol>
          <li class="select input optional">
            <%= f.label :school_name %>
            <%= f.select :school_id, options_for_select(School.all.map{ |school| ["#{school.school_name}", school.id] }), :prompt=>'Please Select School'  %>
            <p class="inline-errors">
              <%=@student.errors[:school_id].join(",") %> 
            </p>
          </li>

          <li class="string input optional stringish">
            <%= f.label :first_name %>
            <%= f.text_field :first_name, autofocus: true %>
            <p id="first_name_error" class="inline-errors">
              <%=@student.errors[:first_name].join(",") %> 
            </p>
          </li>

          <li class="string input optional stringish">
            <%= f.label :middle_name %>
            <%= f.text_field :middle_name, autofocus: true %>
          </li>

          <li class="string input optional stringish">
            <%= f.label :last_name %>
            <%= f.text_field :last_name, autofocus: true %>
            <p id="last_name_error"class="inline-errors">
              <%=@student.errors[:last_name].join(",") %> 
            </p>
          </li>

          <li class="string input optional stringish">
            <%= f.label :dob %>
            <%= f.text_field :dob, autofocus: true,readonly: true %>
            <p id= "student_dob_error"class="inline-errors">
              <%=@student.errors[:dob].join(",") %> 
            </p>
          </li>

          <li class="string input optional stringish">
            <%= f.label :address_line_1 %> 
            <%= f.text_field :address1, autocomplete: "off" %>
          </li>

          <li class="string input optional stringish">
            <%= f.label :address_line_2 %> 
            <%= f.text_field :address2, autocomplete: "off" %>
          </li>

          <li class="string input optional stringish">
            <%= f.label :address_line_3 %> 
            <%= f.text_field :address3, autocomplete: "off" %>
          </li>

          <li class="string input optional stringish">
            <%= f.label :country %> 
            <%= f.select :country, region_options_for_select(only_us_and_canada),{},:class=>"form-control" %>
          </li>


          <li class="string input optional stringish">
            <%= f.label :state %> 
            <%= f.text_field :state, autocomplete: "off" %>
          </li>

          <li class="string input optional stringish">
            <%= f.label :city %> 
            <%= f.text_field :city, autocomplete: "off" %>
          </li>


          <li class="string input optional stringish">
            <%= f.label :zip %> 
            <%= f.text_field :zip, autocomplete: "off" %>
            <p id="zip_error" class="inline-errors">
              <%=@student.errors[:zip].join(" and ") %> 
            </p>
          </li>

          <li class="string input optional stringish">
            <%= f.label :primary_phone %> 
            <%= f.text_field :phone, autocomplete: "off" %>
            <p id="phone_error" class="inline-errors">
              <%=@student.errors[:phone].join(" and ") %> 
            </p>
          </li>

          <li class="string input optional stringish">
            <%= f.label :email %>
            <%= f.email_field :email, autofocus: true %>
            <p  id= "student_email_error" class="inline-errors">
              <%=@student.errors[:email].join(",") %> 
            </p>
          </li>
          

          <li class="string input optional stringish">
            <%= f.label :enroll_date %>
            <%= f.text_field :enroll_date,readonly: true %>
            <p id="student_enroll_date_error"class="inline-errors">
              <%=@student.errors[:enroll_date].join(",") %> 
            </p>
          </li>

          <li class="string input optional stringish">
            <%= f.label :graduation_date %>
            <%= f.text_field :graduation_date,readonly: true %>
            <p id ="student_graduation_date_error"class="inline-errors">
              <%=@student.errors[:graduation_date].join(",") %> 
            </p>
          </li>
        </ol>


        <h2>Classes </h2>

        <div class="input_fields_wrap">
          <input type="button" class="add_field_button" value="Add More Details">

          <div class="education">
            <h3>Class 1</h3>

            <div style="clear:both;"></div>

            <ol>

              <li class="string input optional stringish">
                
               <label for="completion_year">Year</label>
               
               <%= select_tag "completion_year[]", options_for_select([['Freshman ', 'Freshman'], ['Sophomore', 'Sophomore'],['Junior', 'Junior'],['Senior', 'Senior']]),:prompt=>'Please Select '%>
             </li>

             
             
             <li class="string input optional stringish">
              <label for="subject">Subject</label>
              <input type="text" name="subject[]">
            </li>

            <li class="string input optional stringish">
              <label for="course_name">Course Name</label>
              <input type="text" name="course_name[]">
            </li>

            <li class="string input optional stringish">
              <label for="honors">Honors</label>
              <%= select_tag "honors[]", options_for_select([['No ', 'No'], ['Yes', 'Yes']])%>
            </li>

            <li class="string input optional stringish">
             <label for="grade">Grade</label>
             <%= select_tag "grade[]", options_for_select([['A+ ', 'A+'], ['A', 'A'],['A-', 'A-'],['B+', 'B+'],['B', 'B'],['B-', 'B-'],['C+', 'C+'],['C', 'C'],['C-', 'C-'],['D+', 'D+'],['D', 'D'],['D-', 'D-'],['F', 'F'],['CR', 'CR'],['NC', 'NC'],['W', 'W'],['I', 'I']])%>
           </li>
           <li class="string input optional stringish">
             <label for="credit">Credit</label>
             <%= select_tag "credits[]", options_for_select([['0.5 ', '0.5'], ['1.0', '1.0'],['2.0 ', '2.0']])%>
           </li>

           <input type="hidden" name="total_credit[]">
           <input type="hidden" name="gpa_credit[]">
           <input type="hidden" name="gpa_points[]">
           <input type="hidden" name="cumulative_gpa[]">

         </ol>
       </div>
     </div>

     <fieldset class="actions">
      <ol>
        <li id="student_submit_action" class="action input_action ">
         <%= f.submit "Create" %>
       </li>
       <li class="cancel">
        <a href="/admin/students">Cancel</a>
      </li>
    </ol>
  </fieldset>
  <%end%>

</fieldset>
</div>

app/views/admin/students/show.html.erb
<div class="panel">
	<h3>Student Details:</h3>
	<div class="panel_contents">
		<div class="attributes_table ">
			<table class="table table-striped table-responsive table-bordered">
				<tr>
					<th>Name</th><td><%=@student.first_name%> <%=@student.middle_name%> <%=@student.last_name%></td>
				</tr>
				<tr>
					<th>DOB</th><td><%=@student.dob%> </td>
				</tr>
				<tr>
					<th>Address</th><td><%=@student.address1%> , <%=@student.address2%> , <%=@student.address3%></td>
				</tr>
				<tr>
					<th>Country</th><td><%=@country = Carmen::Country.coded(@student.country)%></td>
				</tr>
				<tr>
					<% @subregions = @country.subregions %>
					<% @state = @subregions.coded(@student.state) %>
					<th>State</th>
					<td>
					
						<%if @state.blank?%>

						<%= @student.state%>				
						<%else%>
						<%=@state.name%>
						<%end%>
					</td>
				</tr>
				<tr>
					<th>City</th><td><%=@student.city%></td>
				</tr>
				<tr>
					<th>Zip</th><td><%=@student.zip%></td>
				</tr>
				<tr>
					<th>Phone</th><td><%=@student.phone%></td>
				</tr>
				<tr>
					<th>Email id</th><td><%=@student.email%></td>
				</tr>
				<tr>
					<th>Enrollment Date</th><td><%=@student.enroll_date%></td>
				</tr>
				<tr>
					<th>Graduation Date</th><td><%=@student.graduation_date%></td>
				</tr>
			</table>
			<%x=1%>
			<%@student.subject.length.times do|academic|%>
			<table border="0" cellspacing="0" cellpadding="0">
				<tbody>
					<h3 class="studentH3">Class <%= x %></h3>
					<tr>
						<th>Course Name</th><td><%=@student.course_name[academic]%></td>
					</tr>
					<tr>
						<th>Year</th><td><%=@student.completion_year[academic]%> </td>
					</tr>
					
					<tr>
						<th>Subject</th><td><%=@student.subject[academic]%>	</td>
					</tr>
					<tr>
						<th>Course Name</th><td><%=@student.course_name[academic]%></td>
					</tr>
					<tr>
						<th>Honors</th><td><%=@student.honors[academic]%></td>
					</tr>
					<tr>
						<th>Grade</th><td><%=@student.grade[academic]%></td>
					</tr>
					<tr>
						<th>Credits</th><td><%=@student.credits[academic]%></td>
					</tr>
					</tbody>
			</table>
			<% x = x+1%>
			<%end%>
		</div>
	</div>
</div>