config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :homes do 
    collection do
      get 'dashboard'
    end
  end
  devise_for :users, controllers: {
    sessions: 'user/sessions',
    registrations: 'user/registrations',
    :passwords => "user/passwords"
  }

  authenticated :user do
    devise_scope :user do
      
      root :to => 'homes#index'

    end

  end 
  unauthenticated :user do
    devise_scope :user do
      get "/" => "homes#index"
    end
  end
  
  get '/homes/about'
  post "subscriptions/webhook"
  get '/schools/subregion_options' => 'schools#subregion_options'
  get '/students/subregion_options' => 'students#subregion_options'
  devise_scope :user do
    get '/user/registrations/subregion_options' => 'user/registrations#subregion_options'
  end
  get '/students/:id/view_pdf', to: 'students#view_pdf', as: :view_pdf
  get '/students/checkemail', to: 'students#checkemail', as: :checkemail
  get '/schools/checkemail', to: 'students#checkemail', as: :checkemail_school
  get 'schools/user_detail_copy'
  get 'schools/school_detail_copy'
  
  resources :schools do
    resources :students    
  end

  controller :pages do
    get :about
    get :contact, to: 'pages#contact'
    post 'contact', to: 'pages#create'
  end

  
  resources :subscriptions
  resources :plans
  resources :transactions
  

end

app/models/school.rb
class School < ActiveRecord::Base
	
	validates :school_name,:presence => true 
	# validates :zip,length: { is: 7 ,message: "Zip code length should be 7"}
	validates :email, uniqueness: true
	# validates :phone,numericality:{ only_integer: true ,message:"Phone number should be numeric"},length: { is: 10 ,message: "Phone number length should be 10"}
	
	belongs_to :user
	has_many :students,dependent: :destroy
	validates :user_id,  :presence => {:message => "Please select a user" }
  #validates_format_of :email,:with => Devise::email_regexp

end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
	before_filter :authenticate_user!,except:[:subregion_options]
	load_and_authorize_resource except: [:user_detail_copy,:school_detail_copy , :subregion_options]
	def index
        if current_user.school.blank?
            flash[:notice]= "No School has been created yet"
            redirect_to new_school_path
        else
		  @school = current_user.school
        end
	end 
	def new
		@school = School.new
	end
    def checkemail
        if School.where('email = ?', params[:email]).count == 0
            render json: {:email=>'not exist'}
        else
            render json: {:email=>'exist'}
        end
    end
	def create
		if !current_user.school
			@school = School.new(school_params)
			@school.user_id = current_user.id
			if @school.save
			 redirect_to new_school_student_path(@school.id)
            else
             render 'new'
            end
		else
			flash[:notice]= "User has already School"
			redirect_to schools_path
		end
	end
	def show
		@school =School.find(params[:id])
		respond_to do |format|
			format.html
			format.pdf do
				@pdf = render_to_string pdf: "school" ,:template => 'schools/show.html.erb',
    			# print_media_type: true ,
    			layout:'pdf.html'
    			send_data(@pdf, :filename => @school.school_name,  :type=>"application/pdf")
    		end
    	end
    end
    def edit
    	@school = School.find(params[:id])
    end
    def destroy
    	@school = School.find(params[:id])
    	@school.destroy
    	redirect_to schools_path
    end 
    def update
    	@school = School.find(params[:id])
    	if @school.update(school_params)
    		redirect_to schools_path
    	else
    		render 'edit'
    	end
    end
    def user_detail_copy
    	@user = User.find(current_user)
    	render json:@user
    end
    def school_detail_copy
    	@school = School.find_by_user_id(current_user)
    	render json:@school
    end
    def subregion_options
    	render partial: 'subregion_select'
    end
    private
    def school_params
    	params.require(:school).permit(:school_name , :admin_name, :address1,:address2 , :address3 , :country , :state , :city, :zip , :phone,:email, :academic_term, :grading_scale,:logo)
    end

end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_school_form.html.erb
<div class="mini-title-head-bar logiq1">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <ol class="greybeadcrub">
          <ul class="greybeadcrub"><li><%= link_to 'Home',root_path %></li>
              <li class="active">Create New School</li>
          </ul>                    
        </ol>
      </div>
    </div>
  </div>
</div>
    
    

<div class="container">
  <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
    <% if alert %>
      <center><p class="alert alert-danger"><%= alert %></p></center>
    <% end %>
    <% if flash[:notice] %>
      <center><p class="alert alert-success"><%= flash[:notice] %></p></center>
    <% end %>
      <div class="panel panel-default">
        <div class="panel-heading"> 
          <strong class="">Create New School</strong>
        </div>
        <div class="panel-body">
          <div class="form-group tplgin2">
            <input type= checkbox , class = 'submittable'> Copy user details
          </div>
          <%= form_for @school do|f|%>
            <div class="form-group required">
              <%= f.label :school_name, :class=>"col-sm-3 control-label rigys1" %>
              <div class="col-sm-9">
                <%= f.text_field :school_name, autofocus: true,:class=>"form-control"  %>
              </div>
              <span class="inline-errors">
                <%=@school.errors[:school_name].join(",") %> 
              </span>
            </div>
            <div class="form-group required">
              <%= f.label :admin_name, :class=>"col-sm-3 control-label rigys1" %>
              <div class="col-sm-9">
                <%= f.text_field :admin_name, autofocus: true,:class=>"form-control"  %>
              </div>
              <span class="inline-errors">
                <%=@school.errors[:admin_name].join(",") %> 
              </span>
            </div>
            <div class="form-group">
              <%= f.label :address_line_1,:class=>"col-sm-3 control-label rigys1" %> 
              <div class="col-sm-9">
                <%= f.text_field :address1, autocomplete: "off",:class=>"form-control" %>
              </div>
              <span class="inline-errors">
                <%=@school.errors[:address1].join(",") %> 
              </span>
            </div>
            <div class="form-group">
              <%= f.label :address_line_2,:class=>"col-sm-3 control-label rigys1" %> 
              <div class="col-sm-9">
                <%= f.text_field :address2, autocomplete: "off",:class=>"form-control" %>
              </div>
              <span class="inline-errors">
                <%=@school.errors[:address2].join(",") %> 
              </span>
            </div>
            <div class="form-group">
              <%= f.label :address_line_3,:class=>"col-sm-3 control-label rigys1" %> 
              <div class="col-sm-9">
                <%= f.text_field :address3, autocomplete: "off",:class=>"form-control" %>
              </div>
              <span class="inline-errors">
                <%=@school.errors[:address3].join(",") %> 
              </span>
            </div>
            <div class="form-group required">
              <%= f.label :country,:class=>"col-sm-3 control-label rigys1" %>
              <div class="col-sm-9">
                <%= f.select :country, region_options_for_select(only_us_and_canada),{},:class=>"form-control" %>
              </div>
              <span class="inline-errors">
                <%=@school.errors[:country].join(",") %> 
              </span>  
            </div>
            <div class="form-group">
              <%= f.label :state,:class=>"col-sm-3 control-label rigys1" %>
              <div class="col-sm-9">
                <%= render partial: 'subregion_select', locals: {parent_region: f.object.country}%> 
              </div>
              <span class="inline-errors">
                <%=@school.errors[:state].join(",") %> 
              </span>
            </div>
            <div style="clear:both"></div>
            <div class="form-group">
              <%= f.label :city,:class=>"col-sm-3 control-label rigys1" %>
              <div class="col-sm-9">
                <%= f.text_field :city, autocomplete: "off",:class=>"form-control"  %>
              </div>
              <span class="inline-errors">
                <%=@school.errors[:city].join(",") %> 
              </span>
            </div>
            <div class="form-group">
              <%= f.label :zip,:class=>"col-sm-3 control-label rigys1" %>
              <div class="col-sm-9">
                <%= f.text_field :zip, autocomplete: "off",:class=>"form-control" %>
              </div>
              <span class="inline-errors">
                <%=@school.errors[:zip].join(",") %> 
              </span>
            </div>
            <div class="form-group">
              <%= f.label :primary_phone,:class=>"col-sm-3 control-label rigys1" %>
              <div class="col-sm-9">
                <%= f.text_field :phone, autocomplete: "off",:class=>"form-control" %>
              </div>
              <span class="inline-errors">
                <%=@school.errors[:phone].join(",") %> 
              </span>
            </div>
            <div class="form-group required">
              <%= f.label :email, :class=>"col-sm-3 control-label rigys1" %>
              <div class="col-sm-9" id="email_div_school">
                <%= f.email_field :email, autofocus: true,:class=>"form-control",:required => true %> 
              </div>
              <span class="inline-errors">
                <%=@school.errors[:email].join(",") %> 
              </span>
            </div>
            <div class="form-group">
              <%= f.label :academic_term,:class=>"col-sm-3 control-label rigys1" %>
              <div class="col-sm-6">
                <%= f.select :academic_term, [["Semester", "semester"], ["Quarter","quarter"]],{},{:class=>"form-control"} %>
              </div>
              <span class="inline-errors">
                <%=@school.errors[:academic_term].join(",") %> 
              </span>
            </div>
            <div class="form-group">
              <%= f.label :grading_scale,:class=>"col-sm-3 control-label rigys1" %>
              <div class="col-sm-6">
                <%= f.select :grading_scale, [["7", 7], ["10", 10]],{},{:class=>"form-control"}  %>
              </div>
              <span class="inline-errors">
                <%=@school.errors[:grading_scale].join(",") %> 
              </span>
            </div>
           <div class="chk-bx-mar">
           <div class="panel-heading-bg3"> 
              <strong class="">Please Choose Logo</strong>
           </div>
          <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
              <%= f.radio_button :logo, 'logo1.png' %> <img alt="images" src="/assets/logo1.png" width="128" height="128"/>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
              <%= f.radio_button :logo, 'logo2.png' %> <img alt="images" src="/assets/logo2.png" width="128" height="128"/>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
               <%= f.radio_button :logo, 'logo3.png' %> <img alt="images" src="/assets/logo3.png" width="128" height="128"/>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
               <%= f.radio_button :logo, 'logo4.png' %> <img alt="images" src="/assets/logo4.png" width="128" height="128"/>
            </div>
          </div>

        </div>
            <div class="form-group last">
              <div class="col-sm-offset-3 col-sm-9">
                <a>
                  <%= f.submit "Create", :class=>"btn btn-info" %>
                </a>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/schools/_schooledit_form.html.erb

<div class="mini-title-head-bar logiq1">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <ol class="greybeadcrub">
          <ul class="greybeadcrub"><li><%= link_to 'Home',root_path %></li>
              <li class="active">Edit School Details</li>
          </ul>                    
        </ol>
      </div>
    </div>
  </div>
</div>
    
    

<div class="container">
  <div class="row">
  <%= form_for @school do|f|%>
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
    <% if alert %>
      <center><p class="alert alert-danger"><%= alert %></p></center>
    <% end %>
    <% if flash[:notice] %>
      <center><p class="alert alert-success"><%= flash[:notice] %></p></center>
    <% end %>
      <div class="panel panel-default">
        <div class="panel-heading"> 
          <strong class="">Edit School Details</strong>
        </div>
        <div class="panel-body ">
          
            <div class="form-group required">
              <%= f.label :school_name, :class=>"col-sm-3 control-label rigys1" %>
              <div class="col-sm-9">
                <%= f.text_field :school_name, autofocus: true,:class=>"form-control"  %>
              </div>
              <span class="inline-errors">
                <%=@school.errors[:school_name].join(",") %> 
              </span>
            </div>
            <div class="form-group required">
              <%= f.label :admin_name, :class=>"col-sm-3 control-label rigys1" %>
              <div class="col-sm-9">
                <%= f.text_field :admin_name, autofocus: true,:class=>"form-control"  %>
              </div>
              <span class="inline-errors">
                <%=@school.errors[:admin_name].join(",") %> 
              </span>
            </div>
            <div class="form-group">
              <%= f.label :address_line_1,:class=>"col-sm-3 control-label rigys1" %> 
              <div class="col-sm-9">
                <%= f.text_field :address1, autocomplete: "off",:class=>"form-control" %>
              </div>
              <span class="inline-errors">
                <%=@school.errors[:address1].join(",") %> 
              </span>
            </div>
            <div class="form-group">
              <%= f.label :address_line_2,:class=>"col-sm-3 control-label rigys1" %> 
              <div class="col-sm-9">
                <%= f.text_field :address2, autocomplete: "off",:class=>"form-control" %>
              </div>
              <span class="inline-errors">
                <%=@school.errors[:address2].join(",") %> 
              </span>
            </div>
            <div class="form-group">
              <%= f.label :address_line_3,:class=>"col-sm-3 control-label rigys1" %> 
              <div class="col-sm-9">
                <%= f.text_field :address3, autocomplete: "off",:class=>"form-control" %>
              </div>
              <span class="inline-errors">
                <%=@school.errors[:address3].join(",") %> 
              </span>
            </div>
            <div class="form-group required">
              <%= f.label :country,:class=>"col-sm-3 control-label rigys1" %>
              <div class="col-sm-9">
                <%= f.select :country, region_options_for_select(only_us_and_canada,@school.country),{},:class=>"form-control" %>
              </div>
              <span class="inline-errors">
                <%=@school.errors[:country].join(",") %> 
              </span>  
            </div>
            <div class="form-group">
              <%= f.label :state,:class=>"col-sm-3 control-label rigys1" %>
              <div class="col-sm-9">
                <%= render partial: 'subregion_select', locals: {parent_region: f.object.country}%> 
              </div>
              <span class="inline-errors">
                <%=@school.errors[:state].join(",") %> 
              </span>
            </div>
            <div style="clear:both"></div>
            <div class="form-group">
              <%= f.label :city,:class=>"col-sm-3 control-label rigys1" %>
              <div class="col-sm-9">
                <%= f.text_field :city, autocomplete: "off",:class=>"form-control"  %>
              </div>
              <span class="inline-errors">
                <%=@school.errors[:city].join(",") %> 
              </span>
            </div>
            <div class="form-group">
              <%= f.label :zip,:class=>"col-sm-3 control-label rigys1" %>
              <div class="col-sm-9">
                <%= f.text_field :zip, autocomplete: "off",:class=>"form-control" %>
              </div>
              <span class="inline-errors">
                <%=@school.errors[:zip].join(",") %> 
              </span>
            </div>
            <div class="form-group">
              <%= f.label :primary_phone,:class=>"col-sm-3 control-label rigys1" %>
              <div class="col-sm-9">
                <%= f.text_field :phone, autocomplete: "off",:class=>"form-control" %>
              </div>
              <span class="inline-errors">
                <%=@school.errors[:phone].join(",") %> 
              </span>
            </div>
            <div class="form-group required">
              <%= f.label :email, :class=>"col-sm-3 control-label rigys1" %>
              <div class="col-sm-9">
                <%= f.email_field :email, autofocus: true,:class=>"form-control",:required => true %> 
              </div>
              <span class="inline-errors">
                <%=@school.errors[:email].join(",") %> 
              </span>
            </div>
            <div class="form-group">
              <%= f.label :academic_term,:class=>"col-sm-3 control-label rigys1" %>
              <div class="col-sm-6">
                <%= f.select :academic_term, [["Semester", "semester"], ["Quarter","quarter"]], {},{:class=>"form-control"} %>
              </div>
              <span class="inline-errors">
                <%=@school.errors[:academic_term].join(",") %> 
              </span>
            </div>
            <div class="form-group">
              <%= f.label :grading_scale,:class=>"col-sm-3 control-label rigys1" %>
              <div class="col-sm-6">
                <%= f.select :grading_scale, [["7", 7], ["10", 10]],{},{:class=>"form-control"}  %>
              </div>
              <span class="inline-errors">
                <%=@school.errors[:grading_scale].join(",") %> 
              </span>
            </div>
          
          
        </div>

        <div class="chk-bx-mar">
           <div class="panel-heading-bg2"> 
              <strong class="">Please Choose Logo</strong>
           </div>
          <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
              <%= f.radio_button :logo, 'logo1.png' %> <img alt="images" src="/assets/logo1.png" width="128" height="128"/>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
              <%= f.radio_button :logo, 'logo2.png' %> <img alt="images" src="/assets/logo2.png" width="128" height="128"/>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
               <%= f.radio_button :logo, 'logo3.png' %> <img alt="images" src="/assets/logo3.png" width="128" height="128" />
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
               <%= f.radio_button :logo, 'logo4.png' %> <img alt="images" src="/assets/logo4.png" width="128" height="128" />
            </div>
          </div>

        </div>
              
              
          <div class="panel-footer rptrq2">
          <div class="col-lg-12 col-md-6 col-sm-12 col-xs-12 rptrq1">
              <%= f.submit "Update",:class=>"btn btn-success" %>
              <%= link_to "Back", :back,:class=>"btn btn-primary"%>
          </div>  
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>


app/views/schools/_subregion_select.html.erb
<div id="order_state_code_wrapper">
  <% parent_region ||= params[:parent_region] %>
  <% country = Carmen::Country.coded(parent_region) %>

  <% if country.nil? %>
    <em id="emschool" class="form-control">Please select a country above</em>
  <% elsif country.subregions? %>
    <%= subregion_select(:school , :state, parent_region,{},{:class=>"form-control"}) %>
  <% else %>
    <%= text_field(:school , :state) %>
  <% end %>
</div>

app/views/schools/create.html.erb
Created!!

app/views/schools/edit.html.erb
	
<%= render 'schooledit_form'%>
			

app/views/schools/index.html.erb

<div class="mini-title-head-bar logiq1">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <ol class="greybeadcrub">
          <ul class="greybeadcrub"><li><%= link_to 'Home',root_path %></li>
            <li class="active">School</li>
          </ul>                    
        </ol>
      </div>
    </div>
  </div>
</div>




<div class="container">
  <div class="row">
    <div class="col-lg-10 col-md-10 col-sm-10 col-xs-12 col-md-offset-1">
    <% if alert %>
      <center><p class="alert alert-danger"><%= alert %></p></center>
    <% end %>
    <% if flash[:notice] %>
      <center><p class="alert alert-success"><%= flash[:notice] %></p></center>
    <% end %>
        <div class="panel panel-default">
          <div class="panel-heading"> <strong class="clasq2"><%=@school.school_name%></strong>

          </div>
          <table class="table table-striped table-responsive table-bordered">
            <tbody>
              <tr>
                <th width="77%" rowspan="4" align="center" valign="middle" class="schoolq6"><img class="img-responsive" src="/assets/schoolbg.png" width="698" height="213"></th>
                <td width="23%" align="center" valign="middle">
                  <%= link_to school_path(@school.id),:class=>"btn btn-primary btn-xs schoolq1" do %>
                    <i><span class="glyphicon glyphicon-eye-open"></span></i> View
                  <%end%> 
                </td>
              </tr>
              <tr>
                <td align="center" valign="middle">
                  <%= link_to edit_school_path(@school.id),:class=>"btn btn-info btn-xs schoolq2" do %>
                    <i><span class="glyphicon glyphicon-edit"></span></i> Edit
                  <%end%>
                </td>
              </tr>
              <tr>
                <td align="center" valign="middle">
                  <%= link_to school_students_path(@school.id),:class=>"btn btn-primary btn-xs schoolq4" do %>
                    <i><span class="glyphicon glyphicon-check"></span></i> View Student List
                  <%end%>
                </td>
              </tr>
              <tr>
                <td align="center" valign="middle">
                  <%= link_to new_school_student_path(@school.id),:class=>"btn btn-success btn-xs schoolq5" do %>
                    <i><span class="glyphicon glyphicon-user"></span></i> Add New Student
                  <%end%>
                </td>
              </tr>
            </tbody></table>

          </div>
        </div>

      </div>
    </div>
 

app/views/schools/new.html.erb
<%= render 'school_form'%>

app/views/schools/show.html.erb

<div class="mini-title-head-bar logiq1">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <ol class="greybeadcrub">
          <ul class="greybeadcrub"><li><%= link_to 'Home',root_path %></li>
            <li class="active">School Details</li>
          </ul>                    
        </ol>
      </div>
    </div>
  </div>
</div>



<div class="container">
  <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
    <% if alert %>
      <center><p class="alert alert-danger"><%= alert %></p></center>
    <% end %>
    <% if flash[:notice] %>
      <center><p class="alert alert-success"><%= flash[:notice] %></p></center>
    <% end %>
      <div class="panel panel-default">
        <div class="panel-heading"> <strong class="">School Details</strong>
        </div>
        <table class="table table-striped table-responsive table-bordered">
          <tbody>
            <tr>
              <th class="showdt1">School Name</th>
              <td><%=@school.school_name%></td>
             </tr>
            <tr>
              <th class="showdt1">Admin Name</th>
              <td><%=@school.admin_name%></td>
            </tr>
            <tr>
              <th class="showdt1">Address</th>
              <td><%=@school.address1%>&nbsp; <%=@school.address2%>&nbsp; <%=@school.address3%></td>
            </tr>
            <tr>
              <th class="showdt1">Country</th>
              <td><%=@country = Carmen::Country.coded(@school.country)%></td>
            </tr>
            <tr>
              <% @subregions = @country.subregions %>
              <% @state = @subregions.coded(@school.state) %>
              <th class="showdt1">State</th>
                <td>
                  <%if @state.blank?%>
                    <%= @school.state%>        
                  <%else%>
                    <%=@state.name%>
                  <%end%>
                </td>
            </tr>
            <tr>
              <th class="showdt1">City</th>
              <td><%=@school.city%></td>
            </tr>
            <tr>
              <th class="showdt1">Zip</th>
              <td><%=@school.zip%></td>
            </tr>
            <tr>
              <th class="showdt1">Phone</th>
              <td><%=@school.phone%></td>
            </tr>
            <tr>
              <th class="showdt1">Email id</th>
              <td><%=@school.email%></td>
            </tr>
            <tr>
              <th class="showdt1">Academic Term</th>
              <td><%=@school.academic_term%></td>
            </tr>
            <tr>
              <th class="showdt1">Grading Scale</th>
              <td><%=@school.grading_scale%></td>
            </tr>
          </tbody>
        </table>
        <div class="panel-footer tplgin6">
          <%= link_to "Back", :back,:class=>'btn btn-primary' %>
        </div>
      </div>
    </div>
  </div>
</div>