config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :homes do 
    collection do
      get 'dashboard'
    end
  end
  devise_for :users, controllers: {
    sessions: 'user/sessions',
    registrations: 'user/registrations',
    :passwords => "user/passwords"
  }

  authenticated :user do
    devise_scope :user do
      
      root :to => 'homes#index'

    end

  end 
  unauthenticated :user do
    devise_scope :user do
      get "/" => "homes#index"
    end
  end
  
  get '/homes/about'
  post "subscriptions/webhook"
  get '/schools/subregion_options' => 'schools#subregion_options'
  get '/students/subregion_options' => 'students#subregion_options'
  devise_scope :user do
    get '/user/registrations/subregion_options' => 'user/registrations#subregion_options'
  end
  get '/students/:id/view_pdf', to: 'students#view_pdf', as: :view_pdf
  get '/students/checkemail', to: 'students#checkemail', as: :checkemail
  get '/schools/checkemail', to: 'students#checkemail', as: :checkemail_school
  get 'schools/user_detail_copy'
  get 'schools/school_detail_copy'
  
  resources :schools do
    resources :students    
  end

  controller :pages do
    get :about
    get :contact, to: 'pages#contact'
    post 'contact', to: 'pages#create'
  end

  
  resources :subscriptions
  resources :plans
  resources :transactions
  

end

app/views/layouts/_footer.html.erb
<div class="footer1">
<footer id="footer">
		<div class="container">
			<div class="row">
				
				<div class="col-sm-3 ">
					<p class="phdr">The Company</p>
					<ul class="contact">
            			
						<li><%= link_to 'About Us',about_path%></li>
						<li><a href="#">Features</a></li>
						<li><%= link_to 'Plans',plans_path%></li>
                        <li><%= link_to 'Contact Us',contact_path%></li>
		  </ul>
				</div>
				<div class="col-sm-3">
					<p class="phdr">Help</p>
					<ul class="contact">
            			
						<li><a href="#">Terms & Conditions</a></li>
						<li><a href="#">Privacy Policy</a></li>
						<li><a href="#">Faq's</a></li>
		  </ul>
				</div>
				<div class="col-sm-3">
					<div class="contact-details">
						<p class="phdr">Contact</p>
							<p><i class="icon icon-envelope"></i> <strong>E-mail: </strong> <a href="mailto:info@transcripts.me">info@transcripts.me</a></p>
						
					</div>
				</div>
				<div class="col-sm-3">
					<p class="phdr">Follow Us</p>
					<div class="social-icons">
						<div class="soc1"><a href="#"><img src="/assets/facebook.png" width="26" height="26" /></a></div>
			            <div class="soc2"><a href="#">Facebook</a></div>
			            <div class="clearfix"></div>
					</div>
				</div>
			</div>
			
		</div>
           <div class="footer6">
      <div class="container">
        <div class="footer7"><img src="/assets/footerlogo.png" width="142" height="50"></div>
        <div class="footer8">© 2015. All Right Reserved</div>
        <div class="text-right powered-by-inveera">Design & Developed By <%= link_to "Inveera Technologies Pvt. Ltd.", "http://inveera.com/", target: "_blank" %></div>
      </div>
    </div>
	</footer>
    </div>

app/views/layouts/_header.html.erb
<div class="container-fluid">
	<div class="header_top">
   <div class="container" >
    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12"><strong>Welcome to Transcripts!</strong></div>
    
    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
     <div class="txtalign-hd">
       <% if user_signed_in? %>
       <% @name = current_user.first_name.to_s() +' '+current_user.last_name.to_s()%>
       <span class="wyttxt-top">Welcome <%= link_to @name,edit_user_registration_path %></span> |
       <span class="glyphicon glyphicon-off"></span>  &nbsp;
          <span class="wyttxt-top">
            <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
          </span>
       <%else%>
       <span class="glyphicon glyphicon-user"></span> &nbsp;   
        <span class="wyttxt-top"><%= link_to 'Sign up', new_user_registration_path %></span>
          &nbsp;&nbsp;   
       <span class="glyphicon glyphicon-lock"></span>  &nbsp;
       <span class="wyttxt-top"><%= link_to 'Login', new_user_session_path %></span>
       <%end%>
     </div>
   </div>
 </div>
</div>
</div>
<div class="container">
  <div class="row">
    <div class="col-lg-5 col-md-6 col-sm-12 col-xs-12">
      <img class="img-responsive" src="/assets/logo.png" alt="" />
    </div>
    <div class="col-lg-7 col-md-7 col-sm-12 col-xs-12 marpadz">
      <div id='cssmenu' style="margin-top:20px;">
        <ul>
          <li><%= link_to 'Home',root_path %></li>  
          <%if current_user%>
            <li> <%= link_to 'Dashboard',dashboard_homes_path %></li>
          <%end%>
          <li><a href="#">Features</a></li>
          <li><%= link_to 'About Us',about_path%></li>
          <li><a href="http://www.blog.transcripts.me" target="new" >Blog</a></li>
          <li><%= link_to 'Contact Us',contact_path%></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<title>EducationalRecord</title>
	<% if !request.path.include? "admin"%>
	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%end%>
	<%= csrf_meta_tags %>
</head>
<body>
	<% if !request.path.include? "admin"%>
		<%= render 'layouts/header'%>
		
		
	<% end %>
	
	<%= yield %>

	<% if !request.path.include? "admin"%>
		<%= render 'layouts/footer'%>
	<%end%>
</body>
</html>